# Site Info
title: Jerry's Blog
tagline:
description:
url: http://jjerry-k.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: Jerry
  description:
  gravatar: 22a6447c0c965de55f4ce9691aed2af4
  contact:
    #linkedin:  https://www.linkedin.com/in/gichanglee/
    github:    https://github.com/jjerry-k
    facebook:  https://www.facebook.com/jerry.kim.566
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:jaeyeol2931@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Contents:
    - '/blog/'
    #- { Archive: '/blog/categories/' }
    #- { Tags: '/blog/tags/' }
    - { Blog: '/blog/blog/'}
    - { Python: '/blog/python/'}
    - { Ubuntu: '/blog/ubuntu/'}
    - { Living: '/blog/living/'}
    - { Deep Learning: '/blog/deeplearning/'}
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://jjerry-k.github.io/public/img/jerry.jpg
  caption:

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-126636477-1' # leave blank if you don't want google analytics
disqus_short_name: 'jerry' # leave blank if you don't want disqus
